apiVersion: v1
kind: ServiceAccount
metadata:
  name: co11yctor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: co11yctor
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: co11yctor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: co11yctor
subjects:
  - kind: ServiceAccount
    name: co11yctor
    namespace: default
